site_name: CarolApp Monitor
repo_url: https://github.com/RWallan/carol-app-monitor
repo_name: RWallan/carol-app-monitor
edit_uri: tree/main/docs

theme:
  name: material
  language: en
  logo: assets/images/logo_reduced.png
  favicon: assets/images/favicon.png
  palette:
    primary: deep orange
    accent: deep orange
    scheme: slate
  features:
    - content.tabs.link
    - content.code.copy
    - navigation.footer

nav:
- CarolApp Monitor: index.md
- TOTVS Carol:
  - carol/index.md
- User Guide: 
  - tutorial/index.md
- API:
  - api/carol_api.md
  - api/utils.md
- How to Contribute:
  - contribute/index.md

markdown_extensions:
  - attr_list
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - codehilite
  - pymdownx.inlinehilite

extra_css:
  - stylesheets/css/extra.css
  - stylesheets/css/termynal.css

plugins:
  - macros
  - mkdocstrings:
      handlers:
        python:
          paths: [carol_app_monitor]
  - termynal
