name: test_pipeline
on:
  push:
    branches:
      - "main"

  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Enviromnent setup
        uses: actions/checkout@v3

      - name: Python install
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.0"

      - name: Install poetry
        run: pip install poetry

      - name: Install project dependencies
        run: poetry install --without doc

      - name: Run tests
        run: poetry run task test --cov-report=xml
        env:
          CAROLAPPNAME: ${{ secrets.CAROLAPPNAME }}
          CAROLTENANT: ${{ secrets.CAROLTENANT }}
          CAROLORGANIZATION: ${{ secrets.CAROLORGANIZATION }}
          CAROLAPPOAUTH: ${{ secrets.CAROLAPPOAUTH }}
          CAROLCONNECTORID: ${{ secrets.CAROLCONNECTORID }}

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
